# Generated by Django 2.2.24 on 2021-12-08 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('booking_number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('loading_port', models.CharField(max_length=50)),
                ('discharge_port', models.CharField(max_length=50)),
                ('departure_date', models.CharField(max_length=10)),
                ('arrival_date', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ('loading_port',),
            },
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('vin_num', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('weight', models.CharField(max_length=50)),
                ('booking', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('booking',),
            },
        ),
    ]
