# Generated by Django 2.2.24 on 2021-12-09 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookings',
            options={'ordering': ('departure_date',)},
        ),
    ]
